"""Output filtering — PII redaction, safety warnings, compliance stamps."""

from __future__ import annotations

import re
from dataclasses import dataclass

from src.utils.logger import get_logger

logger = get_logger("guardrails.output")

_PII_REDACTION_RULES = [
    (re.compile(r"\b\d{3}-\d{2}-\d{4}\b"), "[REDACTED_SSN]"),
    (re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"), "[REDACTED_EMAIL]"),
    (re.compile(r"\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b"), "[REDACTED_PHONE]"),
    (re.compile(r"\bMRN\s*[:#]?\s*\d{6,}\b", re.IGNORECASE), "[REDACTED_MRN]"),
    (re.compile(r"\b\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b"), "[REDACTED_CARD]"),
    # Patient names in format "Patient: First Last" or "Subject: First Last"
    (re.compile(r"(?:patient|subject)\s*:\s*[A-Z][a-z]+\s+[A-Z][a-z]+", re.IGNORECASE), "[REDACTED_PATIENT_NAME]"),
]


@dataclass
class FilterResult:
    """Result of output filtering."""
    filtered_text: str
    redactions_applied: int
    warnings: list[str]


class OutputFilter:
    """Filter and sanitize LLM outputs for compliance and safety."""

    def __init__(self):
        self._redaction_rules = _PII_REDACTION_RULES

    def filter(self, text: str) -> FilterResult:
        """Apply all output filters."""
        redactions = 0
        warnings: list[str] = []
        filtered = text

        # PII redaction
        for pattern, replacement in self._redaction_rules:
            matches = pattern.findall(filtered)
            if matches:
                redactions += len(matches)
                filtered = pattern.sub(replacement, filtered)

        # Check for medical advice disclaimers
        medical_advice_indicators = [
            "you should take",
            "i recommend you",
            "start taking",
            "stop taking",
            "change your dose",
            "this drug will cure",
        ]
        for indicator in medical_advice_indicators:
            if indicator.lower() in filtered.lower():
                warnings.append(
                    "Output may contain direct medical advice. "
                    "Adding disclaimer: This is for research purposes only, "
                    "not medical advice."
                )
                break

        # Check for absolute claims about drug efficacy
        absolute_claims = [
            r"\b(?:will\s+definitely|guaranteed\s+to|100%\s+effective|certainly\s+cures)\b",
        ]
        for pattern_str in absolute_claims:
            if re.search(pattern_str, filtered, re.IGNORECASE):
                warnings.append(
                    "Output contains absolute efficacy claims. "
                    "All efficacy statements should be qualified with confidence intervals "
                    "and supporting data."
                )
                break

        if redactions > 0:
            logger.info("Redacted %d PII instance(s) from output", redactions)

        return FilterResult(
            filtered_text=filtered,
            redactions_applied=redactions,
            warnings=warnings,
        )

    def add_compliance_footer(self, text: str, doc_type: str = "general") -> str:
        """Append compliance disclaimer to output."""
        disclaimers = {
            "general": (
                "\n\n---\n*DISCLAIMER: This information is generated by PharmaAgent Pro "
                "for research and decision-support purposes only. It does not constitute "
                "medical advice. All clinical decisions should be made by qualified "
                "healthcare professionals.*"
            ),
            "regulatory": (
                "\n\n---\n*CONFIDENTIAL — For Regulatory Use Only. This document was "
                "generated by PharmaAgent Pro and requires review by qualified regulatory "
                "affairs personnel before submission. Document contents must be verified "
                "against source data.*"
            ),
            "safety": (
                "\n\n---\n*SAFETY NOTICE: This safety assessment is auto-generated and "
                "must be reviewed by the pharmacovigilance team before any action is taken. "
                "Serious adverse events require immediate reporting per ICH E2A guidelines.*"
            ),
        }
        return text + disclaimers.get(doc_type, disclaimers["general"])
